export const projectsData = [
  {
    title: "Wanderlust-Listing Platform",
    description: "Wanderlust is a full-stack travel listing platform with secure user authentication, allowing users to create, view, edit, and delete stay listings with images, pricing, and locations. It features map integration for accurate location display and a review system for user feedback.",
    techStack: ["Node.js", "MongoDB", "Express", "EJS"],
    image: "/wanderLust.png",
    liveDemo: "https://wanderlust-men.onrender.com/",
    sourceCode: "https://github.com/Avramana11/wanderlust-men",
  },
  {
    title: "Top 10 OWASP Vulnerabilities",
    description: "An interactive learning platform that explains the Top 10 OWASP vulnerabilities using beginner-friendly lessons, vulnerable vs secure code examples, and quizzes to reinforce web security concepts.",
    techStack: ["React-Vite", "Node.js", "Express", "MongoDB", "TailwindCSS"],
    image: "OSWAP.png",
    liveDemo: "https://top10-oswap.vercel.app/",
    sourceCode: "https://github.com/Avramana11/Top10-OSWAP",
  },
  {
    title: "Blog Platform",
    description: "A full-stack blog platform built with the MERN stack and Redux Toolkit for state management, allowing users to create, edit, and manage blog posts with secure authentication and a responsive user experience.",
    techStack: ["React-Vite", "Node.js", "Express", "MongoDB", "TailwindCSS"],
    image: "Blog.png",
    liveDemo: "https://blog-9j4h.onrender.com/",
    sourceCode: "https://github.com/Avramana11/Blog",
  },
  {
    title: "Weather-App",
    description: "A full-stack web application built with MongoDB, Express, React, and Node.js that provides real-time weather updates for any city. Features include dynamic search, responsive design, and visually appealing weather data display.",
    techStack: ["React", "API"],
    image: "Weather.png",
    liveDemo: "https://weather-app-uw4y.vercel.app/",
    sourceCode: "https://github.com/Avramana11/weather-app",
  },
  {
    title: "Portfolio",
    description: "A personal portfolio website built with React to showcase my projects, skills, and experience. It features a responsive UI, modern component-based design, and smooth navigation for an engaging user experience.",
    techStack: ["React", "TailwindCSS"],
    image: "portfoilio.png",
    liveDemo: "https://portfolio-henna-three-74.vercel.app/",
    sourceCode: "https://github.com/Avramana11/Portfolio",
  },
    {
    title: "Nursery",
    description:"A full-stack nursery web application where users can explore different plants, gardening tools, and nursery products. Developed using the MERN stack, the platform provides dynamic product listings, responsive design, and efficient database management for plant details and availability.",
    techStack: ["MongoDB", "Express", "React", "Node.js"],
    image: "Nursery.png",
    liveDemo: "#",
    sourceCode: "#",
  },
];
